### ISSUE TITLE
cannot view tag when trying to stage dataset with long data type name

### ISSUE THREAD

**Issue by kitchell** [brain-life/warehouse#113]
![screen shot 2017-10-24 at 8 38 53 pm](https://user-images.githubusercontent.com/25829572/31974847-98bef4c0-b8fb-11e7-9405-58b72c4453a6.png)
I can't see the tag for the LB spectrum output when trying to stage the dataset

**Comment by soichih** [comment]
I've increase the size of the dialog so that you can see all tags. 

@kitchell I've been meaning to ask.. Can we update "something_output" to just "something" for all datatype names? I think "output" can be implied and not necessary. It's just making the datatype name long unnecessary and it's causing various other UI related issues on other places.
