### ISSUE TITLE
Private projects should have private apps and data

### ISSUE THREAD

**Issue by francopestilli** [brain-life/warehouse#89]
A project is a collection of data and Apps.

Ideally, when a private project is created apps and data should be allowed to be set as private. This means that the apps will not be available on the Apps tab and will not run unless the user has permissions on the project.

Obviously, the github.com repository could still be available and open, that is a choice left to the user.

**Comment by soichih** [comment]
Brain-Life currently requires all apps to be public on github - so that it can clone / update apps from github at runtime. I believe we could support private repo by creating Brain-Life user on github and ask developer to make it a member of the private repo, but I need to experiment.

For making apps part of project, I will add a project field on app record - and let developer pick a project that app belongs to during the registration. Then, similar to datasets, user can see / view apps that are part of public project, or member of the project that apps are registered under.

**Comment by francopestilli** [comment]
I would be fine if Apps were public on github.com but private on Brain-Life. This could be implemented only by changing the code on brain-life.

**Comment by soichih** [comment]
Roughly implemented as discussed. 

There are some *common* apps that doesn't belong to any specific projects (like acpcalign / freesurfer, etc..) For now, I've implemented so that, application developer can choose to not set the project membership for the app. If it's not set, brain-life will expose the app to all users just like they are now.

**Comment by francopestilli** [comment]
Awesome. I am not sure it shows up yet. Does it?

**Comment by soichih** [comment]
I just released it.

**Comment by kitchell** [comment]
private apps should be able to be tied to multiple private projects, if possible.

**Comment by soichih** [comment]
I will update it.

**Comment by soichih** [comment]
@kitchell @bcmcpher I've updated so that app can have multiple projects set. For all apps that you'd like to keep them hidden, please update those app with proper list of projects.
